### ISSUE TITLE
Access Error

### ISSUE THREAD

**Issue by Hamcastle** [benjaminrwilson/inequity-release#1]
Hi,

When I run your get_data.sh script, I get a 403 access-disabled error message. Are you no longer making the data for this project public, or has it been moved to another storage location, perhaps? 

Thanks!

**Comment by benjaminrwilson** [comment]
The server appears to have an issue. I will look into this, and get back to you ASAP.

**Comment by benjaminrwilson** [comment]
I'm terribly sorry this took so long -- we had some AWS account transfer issues that took quite some time. It should be available now!

**Comment by Hamcastle** [comment]
Thanks for this! No trouble about the time 👍
